# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZEquipoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Usuario_equipo',
                'verbose_name': 'Equipo',
            },
        ),
        migrations.AlterModelOptions(
            name='usuarioapp',
            options={'verbose_name': 'Usuario de aplicacion'},
        ),
        migrations.AddField(
            model_name='usuarioapp',
            name='administraEquipos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarioapp',
            name='limiteCantidadEquipos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuarioapp',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='usuarioapp',
            table='Usuario_usuarioApp',
        ),
        migrations.AddField(
            model_name='zequipotrabajo',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_usurioAdminEquipo', to='usuario.UsuarioApp', verbose_name='Administrador del equipo'),
        ),
        migrations.AddField(
            model_name='zequipotrabajo',
            name='usuarios',
            field=models.ManyToManyField(related_name='fk_usuariosDelEquipo', to='usuario.UsuarioApp', verbose_name='Integrantes del equipo'),
        ),
        migrations.AlterUniqueTogether(
            name='zequipotrabajo',
            unique_together=set([('nombre',)]),
        ),
    ]
